#lang scheme
(require "fp-functions.scm")

(define (fp-interpret code) 
   code)

(define (map-symbol-to-function symbol)
  (cond ((equal? symbol 'id) 'fp-id)
        ((equal? symbol 'tl) 'fp-tl)
        ((equal? symbol 'tlr) 'fp-tlr)
        ((equal? symbol 'atom) 'fp-atom)
        ((equal? symbol 'eq) 'fp-eq)
        ((equal? symbol 'null) 'fp-null)
        ((equal? symbol 'reverse) 'fp-reverse)
        ((equal? symbol 'iota) 'fp-iota)
        ((equal? symbol 'distl) 'fp-distl)
        ((equal? symbol 'distr) 'fp-distr)
        ((equal? symbol 'length) 'fp-length)
        ((equal? symbol '-) 'fp--)
        ((equal? symbol '+) 'fp-+)
        ((equal? symbol '*) 'fp-*)
        ((equal? symbol '%) 'fp-%)
        ((equal? symbol '<) 'fp-<)
        ((equal? symbol '>) 'fp->)
        ((equal? symbol 'trans) 'fp-trans)
        ((equal? symbol 'and) 'fp-and)
        ((equal? symbol 'or) 'fp-or)
        ((equal? symbol 'not) 'fp-not)
        ((equal? symbol 'appendl) 'fp-appendl)
        ((equal? symbol 'rot) 'fp-rot)
        ((equal? symbol 'rotr) 'fp-rotr)        
        ((equal? symbol 'o) 'fp-compose)
        ((equal? symbol '[]) 'fp-construct)
        ((equal? symbol '~) 'fp-const)
        ((equal? symbol '->) 'fp-cond)
        ((equal? symbol '/) 'fp-insert)
        ((equal? symbol 'alpha) 'fp-alpha)
        (else null)))

(map-symbol-to-function '/)
(fp-interpret '(id o 1))